import { afterEach, describe, expect, test } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { SqliteInternalRuntimeStore } from '@/lib/control-plane/sqlite-runtime-store';
import { buildControlPlaneOperatorSnapshot } from '@/lib/control-plane/operator-view';
let tempDir:string|null=null; afterEach(()=>{if(tempDir){rmSync(tempDir,{recursive:true,force:true});tempDir=null;}});
function store(){tempDir=mkdtempSync(path.join(tmpdir(),'startup-operator-')); return new SqliteInternalRuntimeStore(path.join(tempDir,'cp.db'));}
describe('Control Plane operator runtime',()=>{
 test('lists persisted workflow snapshots',async()=>{const cp=store(); await cp.createWorkflow({id:'wf-1',state:'DRAFT',revision:0,createdBy:{kind:'agent',id:'lauti'},createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',responsibleResearchAgentId:'lauti',artifacts:[],invalidations:[],metadata:{}}); expect(cp.listWorkflowSnapshots()).toHaveLength(1); const s=await buildControlPlaneOperatorSnapshot(cp); expect(s.counts.workflows).toBe(1); cp.close();});
 test('redrives dead-letter agent tasks and preserves record',()=>{const cp=store(); cp.upsertAgentRuntimeTask({taskId:'task-1',handoffId:'handoff-1',agentId:'john',action:'monitor_open_position',summary:'Monitor',status:'dead_letter',attempts:3,createdAt:'2026-01-01T00:00:00.000Z',availableAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:03.000Z',retryPolicy:{maxAttempts:3,initialDelayMs:1000,backoffMultiplier:2,maxDelayMs:10000,timeoutMs:30000},lastError:'provider_failure',payload:{},policyEvidence:[]}); const r=cp.redriveAgentRuntimeTask({taskId:'task-1',requestedAt:'2026-01-01T00:01:00.000Z',reason:'Provider recovered.'}); expect(r).toMatchObject({status:'queued',attempts:0}); expect(cp.listRuntimeRedrives()[0]).toMatchObject({kind:'agent_task',targetId:'task-1',previousAttempts:3}); cp.close();});
 test('redrives dead-letter handoffs and preserves record',()=>{const cp=store(); cp.enqueueHandoffsIdempotent([{handoffId:'handoff-2',sourceMessageId:'msg-2',sourceTopic:'control-plane.workflow.transitioned',kind:'agent_task',destination:{kind:'agent',id:'yann'},action:'perform_red_desk_review',summary:'Review',status:'dead_letter',attempts:5,createdAt:'2026-01-01T00:00:00.000Z',availableAt:'2026-01-01T00:00:00.000Z',retryPolicy:{maxAttempts:5,initialDelayMs:1000,backoffMultiplier:2,maxDelayMs:60000,timeoutMs:30000},lastError:'runtime_unavailable',policyEvidence:[],payload:{}}]); const r=cp.redriveHandoff({handoffId:'handoff-2',requestedAt:'2026-01-01T00:01:00.000Z',reason:'Runtime recovered.'}); expect(r).toMatchObject({status:'pending',attempts:0}); expect(cp.listRuntimeRedrives()[0]).toMatchObject({kind:'handoff',targetId:'handoff-2',previousAttempts:5}); cp.close();});
});
