import { Brain } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';

export const dynamic = 'force-dynamic';

export default function BrainPage() {
  return (
    <div>
      <PageHeader
        eyebrow="institutional memory"
        title="Startup Brain"
      />

      <div className="max-w-4xl">
        <section className="rounded-lg-t border border-os-border bg-os-surface p-6">
          <div className="flex items-start gap-4">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md-t border border-os-border bg-os-surface2">
              <Brain className="h-5 w-5 text-os-muted" />
            </div>

            <div>
              <div className="text-sm font-semibold">
                Institutional memory is empty
              </div>

              <p className="mt-2 text-sm leading-relaxed text-os-muted">
                The Startup Brain is starting from a clean state.
              </p>

              <p className="mt-2 text-sm leading-relaxed text-os-dim">
                Company knowledge, decisions, experiences, lessons and
                performance history will appear here only after they are
                generated by this company.
              </p>
            </div>
          </div>
        </section>

        <section className="mt-4 grid grid-cols-3 gap-3 max-[900px]:grid-cols-1">
          <div className="rounded-lg-t border border-os-border bg-os-surface p-4">
            <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-os-dim">
              Experiences
            </div>

            <div className="mt-2 text-2xl font-semibold">
              0
            </div>
          </div>

          <div className="rounded-lg-t border border-os-border bg-os-surface p-4">
            <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-os-dim">
              Decisions
            </div>

            <div className="mt-2 text-2xl font-semibold">
              0
            </div>
          </div>

          <div className="rounded-lg-t border border-os-border bg-os-surface p-4">
            <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-os-dim">
              Validated lessons
            </div>

            <div className="mt-2 text-2xl font-semibold">
              0
            </div>
          </div>
        </section>

        <section className="mt-4 rounded-lg-t border border-dashed border-os-border p-5">
          <div className="font-mono text-[10px] uppercase tracking-[0.18em] text-os-dim">
            Memory status
          </div>

          <p className="mt-2 text-sm leading-relaxed text-os-muted">
            No institutional memory is currently loaded.
          </p>

          <p className="mt-1 text-sm leading-relaxed text-os-dim">
            Cognee and the Brain Gateway will be connected in a later
            milestone.
          </p>
        </section>
      </div>
    </div>
  );
}